default:
  @just --list
  
pre-release:
  just check
  just doc
  cargo +stable semver-checks

check:
  cargo +nightly fmt --all
  cargo +nightly clippy --tests --all
  cargo +nightly clippy --tests --all --all-features

doc *args:
  cargo +nightly rustdoc {{args}} --all-features -- --cfg docsrs
