set shell := ["nu", "-c"]

default:
  @just --list
  
pre-release:
  just check
  just doc
  cargo semver-checks

check:
  cargo fmt --all
  cargo clippy --tests --all
  cargo clippy --tests --all --all-features

doc *args:
  cargo rustdoc {{args}} --all-features -- --cfg docsrs
